# Generated by Django 3.1.7 on 2021-05-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexible', '0008_auto_20210520_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexibletwocolumnpage',
            name='offset_2nd_column',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
