# Generated by Django 3.1.7 on 2021-03-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('flexible', '0010_auto_20210304_2048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlexibleTwoColumnPage',
        ),
    ]
