# Generated by Django 3.1.7 on 2021-05-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexible', '0013_flexibleonecolumnpage_top_margin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flexibleonecolumnpage',
            old_name='top_margin',
            new_name='display_title',
        ),
    ]
