# Generated by Django 3.1.7 on 2021-05-26 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexible', '0021_auto_20210526_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexibleonecolumnpage',
            name='display_title',
        ),
    ]
