# Generated by Django 3.1.7 on 2021-05-27 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0014_auto_20210521_1716'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('flexible', '0031_auto_20210527_2219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlexibleOneColumnPageBlueHeader',
        ),
    ]
