# Generated by Django 3.1.7 on 2021-05-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexible', '0045_auto_20210428_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexibleonecolumnpage',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
