# Generated by Django 3.1.7 on 2021-05-14 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesearchpagesettings',
            name='homes_search_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Homes Search Page'),
        ),
    ]
