# Generated by Django 3.1.7 on 2021-02-23 18:38

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210222_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpage',
            name='body',
            field=wagtail.core.fields.StreamField([('hero', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('background_image', wagtail.images.blocks.ImageChooserBlock())]))]),
        ),
    ]
