# Generated by Django 3.1.7 on 2021-05-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20210519_1530'),
        ('base', '0002_homesearchpagesettings_homes_search_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockssettings',
            name='art_cta_col_1_link_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='articles.articlepage', verbose_name='Column 1 Link 1'),
        ),
        migrations.AddField(
            model_name='blockssettings',
            name='art_cta_col_1_link_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='articles.articlepage', verbose_name='Column 1 Link 2'),
        ),
        migrations.AddField(
            model_name='blockssettings',
            name='art_cta_col_1_link_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='articles.articlepage', verbose_name='Column 1 Link 3'),
        ),
        migrations.AddField(
            model_name='blockssettings',
            name='art_cta_col_1_link_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='articles.articlepage', verbose_name='Column 1 Link 4'),
        ),
        migrations.AddField(
            model_name='blockssettings',
            name='art_cta_col_1_title',
            field=models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Column 1 Title'),
        ),
        migrations.AddField(
            model_name='blockssettings',
            name='art_cta_col_2_link_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='articles.articlepage', verbose_name='Column 2 Link 1'),
        ),
        migrations.AddField(
            model_name='blockssettings',
            name='art_cta_col_2_link_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='articles.articlepage', verbose_name='Column 2 Link 2'),
        ),
        migrations.AddField(
            model_name='blockssettings',
            name='art_cta_col_2_link_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='articles.articlepage', verbose_name='Column 2 Link 3'),
        ),
        migrations.AddField(
            model_name='blockssettings',
            name='art_cta_col_2_link_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='articles.articlepage', verbose_name='Column 2 Link 4'),
        ),
        migrations.AddField(
            model_name='blockssettings',
            name='art_cta_col_2_title',
            field=models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Column 2 Title'),
        ),
    ]
