# Generated by Django 3.1.7 on 2021-02-26 20:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210223_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpage',
            name='body',
            field=wagtail.core.fields.StreamField([('hero', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('background_image', wagtail.images.blocks.ImageChooserBlock())])), ('section', wagtail.core.blocks.StreamBlock([('background_image', wagtail.images.blocks.ImageChooserBlock()), ('background_color', wagtail.core.blocks.MultipleChoiceBlock(choices=[('TRANSPARENT', 'transparent'), ('BLUE', 'blue')]))]))]),
        ),
    ]
