# Generated by Django 3.1.7 on 2021-05-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210521_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockssettings',
            old_name='introduction',
            new_name='art_cta_col_intro',
        ),
    ]
