# Generated by Django 3.1.7 on 2021-05-21 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('base', '0006_auto_20210521_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockssettings',
            name='art_cta_button_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Button Link'),
        ),
        migrations.AlterField(
            model_name='blockssettings',
            name='art_cta_button_text',
            field=models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Button text'),
        ),
    ]
