# Generated by Django 3.1.7 on 2021-05-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210521_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesettings',
            name='home_form',
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='home_form_height',
            field=models.IntegerField(default='500', null=True, verbose_name='Wufoo Form Height in pixels'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='home_form_id',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='Wufoo Form ID'),
        ),
    ]
