# Generated by Django 3.1.7 on 2021-04-27 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('base', '0008_auto_20210419_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='mhosettings',
            name='button_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='button_text',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='text',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='title',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
