# Generated by Django 3.1.7 on 2021-05-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210525_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='home_tooltip_text',
            field=models.TextField(default='', max_length=255, null=True, verbose_name='Est Cost tooltip text'),
        ),
    ]
