# Generated by Django 3.1.7 on 2021-04-27 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('base', '0009_auto_20210427_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mhosettings',
            name='button_link',
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='button_external_url',
            field=models.URLField(blank=True, null=True, verbose_name='External link'),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='button_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
