# Generated by Django 3.1.7 on 2021-05-31 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('base', '0009_homepagesettings_home_tooltip_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='home_similar_button_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Similar houses button link'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='home_similar_button_text',
            field=models.CharField(default='Search All Homes', max_length=254, null=True, verbose_name='Similar houses button text'),
        ),
    ]
