# Generated by Django 3.1.7 on 2021-04-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210427_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mhosettings',
            old_name='button_page',
            new_name='forum_button_page',
        ),
        migrations.RenameField(
            model_name='mhosettings',
            old_name='button_text',
            new_name='forum_button_text',
        ),
        migrations.RenameField(
            model_name='mhosettings',
            old_name='text',
            new_name='forum_text',
        ),
        migrations.RenameField(
            model_name='mhosettings',
            old_name='title',
            new_name='forum_title',
        ),
        migrations.RemoveField(
            model_name='mhosettings',
            name='button_external_url',
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='forum_button_external_url',
            field=models.URLField(blank=True, null=True, verbose_name='Button URL'),
        ),
    ]
