# Generated by Django 3.1.7 on 2021-06-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210531_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesearchpagesettings',
            name='filter_price_step',
        ),
    ]
