# Generated by Django 3.1.7 on 2021-04-28 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('base', '0011_auto_20210427_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='mhosettings',
            name='gyh_column_1_text',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='gyh_column_1_title',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='gyh_column_2_text',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='gyh_column_2_title',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='gyh_column_3_text',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='gyh_column_3_title',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='gyh_link_1_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='gyh_link_1_text',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='gyh_link_2_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='gyh_link_2_text',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='gyh_title',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
