# Generated by Django 3.1.7 on 2021-07-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_homesearchpagesettings_filter_price_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesearchpagesettings',
            name='homes_ad_button_link',
        ),
        migrations.RemoveField(
            model_name='homesearchpagesettings',
            name='homes_ad_external_url',
        ),
        migrations.AddField(
            model_name='homesearchpagesettings',
            name='homes_ad_form_height',
            field=models.IntegerField(default='500', null=True, verbose_name='Wufoo Form Height in pixels'),
        ),
        migrations.AddField(
            model_name='homesearchpagesettings',
            name='homes_ad_form_id',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='Wufoo Form ID'),
        ),
    ]
