# Generated by Django 3.1.7 on 2021-04-28 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('base', '0012_auto_20210428_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mhosettings',
            name='forum_button_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Button url'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='forum_button_text',
            field=models.TextField(max_length=255, null=True, verbose_name='Button Text'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='forum_text',
            field=models.TextField(max_length=255, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='forum_title',
            field=models.TextField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='gyh_column_1_text',
            field=models.TextField(max_length=255, null=True, verbose_name='Column 1 text'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='gyh_column_1_title',
            field=models.TextField(max_length=255, null=True, verbose_name='Column 1 title'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='gyh_column_2_text',
            field=models.TextField(max_length=255, null=True, verbose_name='Column 2 text'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='gyh_column_2_title',
            field=models.TextField(max_length=255, null=True, verbose_name='Column 2 title'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='gyh_column_3_text',
            field=models.TextField(max_length=255, null=True, verbose_name='Column 3 text'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='gyh_column_3_title',
            field=models.TextField(max_length=255, null=True, verbose_name='Column 3 title'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='gyh_link_1_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Link 1 url'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='gyh_link_1_text',
            field=models.TextField(max_length=255, null=True, verbose_name='Link 1 text'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='gyh_link_2_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Link 2 url'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='gyh_link_2_text',
            field=models.TextField(max_length=255, null=True, verbose_name='Link 2 text'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='gyh_title',
            field=models.TextField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
