# Generated by Django 3.1.7 on 2021-04-28 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('base', '0013_auto_20210428_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='mhosettings',
            name='partner_1_button_text',
            field=models.TextField(max_length=255, null=True, verbose_name='Column 1 button text'),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='partner_1_button_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Column 1 link url'),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='partner_1_text',
            field=models.TextField(max_length=255, null=True, verbose_name='Column 1 text'),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='partner_1_title',
            field=models.TextField(max_length=255, null=True, verbose_name='Column 1 title'),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='partner_2_button_text',
            field=models.TextField(max_length=255, null=True, verbose_name='Column 2 button text'),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='partner_2_button_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Column 2 link url'),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='partner_2_text',
            field=models.TextField(max_length=255, null=True, verbose_name='Column 2 text'),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='partner_2_title',
            field=models.TextField(max_length=255, null=True, verbose_name='Column 2 title'),
        ),
    ]
