# Generated by Django 3.1.7 on 2021-04-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20210428_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mhosettings',
            old_name='partner_1_button_url',
            new_name='partner_1_button_link',
        ),
        migrations.RenameField(
            model_name='mhosettings',
            old_name='partner_2_button_url',
            new_name='partner_2_button_link',
        ),
    ]
