# Generated by Django 3.1.7 on 2021-04-28 16:32

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20210428_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mhosettings',
            name='partner_1_title',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
