# Generated by Django 3.1.7 on 2021-04-28 20:28

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20210428_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='mhosettings',
            name='resources_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
