# Generated by Django 3.1.7 on 2021-04-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_mhosettings_resources_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mhosettings',
            name='filter_price_max',
            field=models.PositiveIntegerField(default='1500000', verbose_name='Price range max value'),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='filter_price_min',
            field=models.PositiveIntegerField(default='50000', verbose_name='Price range min value'),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='filter_sqft_max',
            field=models.PositiveIntegerField(default='600', verbose_name='Square footage max value'),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='filter_sqft_min',
            field=models.PositiveIntegerField(default='50', verbose_name='Square footage min value'),
        ),
    ]
