# Generated by Django 3.1.7 on 2021-04-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20210430_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='mhosettings',
            name='filter_price_step',
            field=models.PositiveIntegerField(default='10000', verbose_name='Price range widget values step'),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='filter_sqft_step',
            field=models.PositiveIntegerField(default='50', verbose_name='Square footage range widget values step'),
        ),
    ]
