# Generated by Django 3.1.7 on 2021-05-02 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('base', '0022_auto_20210502_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mhosettings',
            name='forum_button_external_url',
            field=models.URLField(blank=True, null=True, verbose_name='Button external URL'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='forum_button_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Button URL from a page'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='gyh_link_1_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Link 1 URL'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='gyh_link_2_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Link 2 URL'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='partner_1_button_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Column 1 link URL'),
        ),
        migrations.AlterField(
            model_name='mhosettings',
            name='partner_2_button_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Column 2 link URL'),
        ),
    ]
