# Generated by Django 3.1.7 on 2021-05-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20210502_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='mhosettings',
            name='home_intro',
            field=models.TextField(max_length=255, null=True, verbose_name='Home introduction'),
        ),
    ]
