# Generated by Django 3.1.7 on 2021-05-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_mhosettings_home_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='mhosettings',
            name='home_button_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Button text'),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='home_small_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Small text'),
        ),
    ]
