# Generated by Django 3.1.7 on 2021-05-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20210507_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mhosettings',
            name='home_small_text',
            field=models.TextField(max_length=255, null=True, verbose_name='Small text'),
        ),
    ]
