# Generated by Django 3.1.7 on 2021-05-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20210507_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='mhosettings',
            name='home_similar_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Similar houses section title'),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='home_verified_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Verified box text'),
        ),
        migrations.AddField(
            model_name='mhosettings',
            name='home_verified_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Verified box title'),
        ),
    ]
