# Generated by Django 3.1.7 on 2021-05-10 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('base', '0027_auto_20210507_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='mhosettings',
            name='home_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Modal Form'),
        ),
    ]
