# Generated by Django 3.1.7 on 2021-05-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='submit_button_text',
            field=models.CharField(blank=True, default='Send', max_length=120),
        ),
    ]
