# Generated by Django 3.1.7 on 2021-02-22 17:56

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homes', '0001_initial'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='partners.partnerpage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='homes.stylecategory'),
        ),
        migrations.AddField(
            model_name='floorplangalleryimage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='floorplangalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='floorplan_gallery_images', to='homes.homepage'),
        ),
        migrations.AddField(
            model_name='elevationgalleryimage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='elevationgalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevation_gallery_images', to='homes.homepage'),
        ),
    ]
