# Generated by Django 3.1.6 on 2021-02-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_auto_20210219_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='manufacturer',
            new_name='partner',
        ),
    ]
