# Generated by Django 3.1.6 on 2021-02-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_auto_20210219_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stylecategory',
            options={'verbose_name_plural': 'styles of homes'},
        ),
    ]
