# Generated by Django 3.1.7 on 2021-03-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_auto_20210304_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceranges',
            name='range',
            field=models.CharField(max_length=255),
        ),
    ]
