# Generated by Django 3.1.7 on 2021-03-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0006_auto_20210304_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='rating',
        ),
        migrations.AddField(
            model_name='homepage',
            name='certified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
