# Generated by Django 3.1.7 on 2021-03-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_auto_20210311_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='certified',
            field=models.BooleanField(default=False),
        ),
    ]
