# Generated by Django 3.1.7 on 2021-05-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0009_auto_20210502_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesindexpage',
            name='intro',
            field=models.TextField(default='', max_length=250),
        ),
    ]
