# Generated by Django 3.1.7 on 2021-05-04 16:45

from django.db import migrations
import mhoapp.theme.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0011_homesindexpage_side_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesindexpage',
            name='side_content',
            field=wagtail.core.fields.StreamField([('blueBoxCTA', mhoapp.theme.blocks.BlueBoxCTA()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('text', wagtail.core.blocks.TextBlock()), ('quote', wagtail.core.blocks.BlockQuoteBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock())], default=''),
        ),
    ]
