# Generated by Django 3.1.7 on 2021-05-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0012_auto_20210504_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesindexpage',
            name='layout',
            field=models.CharField(choices=[('TL', 'Title and paragraph left'), ('TR', 'Title and paragraph right')], default='TL', max_length=2),
        ),
    ]
