# Generated by Django 3.1.7 on 2021-05-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0014_auto_20210504_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesindexpage',
            name='layout',
            field=models.CharField(choices=[('LS', 'Left side shorter'), ('EW', 'Equal width')], default='EW', max_length=2, verbose_name='Columns Width'),
        ),
    ]
