# Generated by Django 3.1.7 on 2021-07-12 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0015_auto_20210529_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesindexpage',
            name='initial_home_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homes.stylecategory', verbose_name='Initial Price Range'),
        ),
    ]
