# Generated by Django 3.1.7 on 2021-05-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0016_auto_20210504_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesindexpage',
            name='initial_price_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='homes.priceranges', verbose_name='Set an initial Price Range'),
        ),
        migrations.AlterField(
            model_name='homesindexpage',
            name='layout',
            field=models.CharField(choices=[('LS', 'Left side shorter'), ('EW', 'Equal width')], default='EW', max_length=2, verbose_name='Heading columns width'),
        ),
    ]
