# Generated by Django 3.1.7 on 2021-07-13 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('homes', '0017_auto_20210713_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylecategory',
            name='style_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
