# Generated by Django 3.1.7 on 2021-05-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0017_auto_20210505_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesindexpage',
            name='initial_price_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homes.priceranges', verbose_name='Set an initial Price Range'),
        ),
    ]
