# Generated by Django 3.1.7 on 2021-05-05 18:34

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0018_auto_20210505_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceranges',
            name='homes_search_page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homes.homesindexpage'),
        ),
    ]
