# Generated by Django 3.1.7 on 2021-09-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0019_auto_20210715_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homesindexpage',
            old_name='two_cols_content',
            new_name='left_col_content',
        ),
        migrations.RenameField(
            model_name='homesindexpage',
            old_name='two_cols_content_shorter',
            new_name='right_col_content',
        ),
    ]
