# Generated by Django 3.1.7 on 2021-05-05 18:35

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0019_priceranges_homes_search_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceranges',
            name='homes_search_page',
        ),
        migrations.AddField(
            model_name='priceranges',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homes_search_page', to='homes.homesindexpage'),
        ),
    ]
