# Generated by Django 3.1.7 on 2021-05-05 18:49

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('homes', '0021_auto_20210505_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceranges',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homes_search_page', to='wagtailcore.page'),
        ),
    ]
