# Generated by Django 3.1.7 on 2021-09-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0021_auto_20210918_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homesindexpage',
            old_name='left_col_content',
            new_name='left_column_content',
        ),
        migrations.RenameField(
            model_name='homesindexpage',
            old_name='right_col_content',
            new_name='right_column_content',
        ),
    ]
