# Generated by Django 3.1.7 on 2021-05-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0022_auto_20210505_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceranges',
            old_name='page',
            new_name='homes_search_page',
        ),
    ]
