# Generated by Django 3.1.7 on 2021-05-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0025_auto_20210505_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesindexpage',
            name='layout',
            field=models.CharField(choices=[('FW', 'Full Width'), ('LS', 'Left side shorter'), ('EW', 'Equal width')], default='FW', max_length=2, verbose_name='Heading columns width'),
        ),
    ]
