# Generated by Django 3.1.7 on 2021-05-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0026_auto_20210505_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesindexpage',
            name='layout',
            field=models.CharField(choices=[('FW', '1 Column - Full width'), ('LS', '2 Columns - Left side smaller'), ('EW', '2 Columns - Equal width')], default='FW', max_length=2, verbose_name='Heading layout'),
        ),
    ]
