# Generated by Django 3.1.7 on 2021-05-06 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_auto_20210506_1541'),
        ('homes', '0034_auto_20210506_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesindexpage',
            name='initial_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.locationcategory', verbose_name='Initial location'),
        ),
        migrations.AlterField(
            model_name='homesindexpage',
            name='initial_price_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homes.priceranges', verbose_name='Initial Price Range'),
        ),
    ]
