# Generated by Django 3.1.7 on 2021-02-24 22:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('partners', '0002_auto_20210224_2203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartnersIndexPage',
            new_name='PartnerTypePage',
        ),
    ]
