# Generated by Django 3.1.7 on 2021-05-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20210513_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerpage',
            name='main_image',
        ),
    ]
