# Generated by Django 3.1.6 on 2021-02-19 20:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20210219_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationcategory',
            options={'verbose_name_plural': 'locations of partners'},
        ),
        migrations.AlterField(
            model_name='partnerpage',
            name='locations',
            field=modelcluster.fields.ParentalManyToManyField(to='partners.LocationCategory'),
        ),
        migrations.AlterField(
            model_name='partnerpage',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='partners.typecategory'),
        ),
    ]
