# Generated by Django 3.1.6 on 2021-02-19 21:08

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20210219_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerpage',
            name='type',
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='types',
            field=modelcluster.fields.ParentalManyToManyField(to='partners.TypeCategory'),
        ),
    ]
