# Generated by Django 3.1.7 on 2021-02-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20210224_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnertypepage',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
