# Generated by Django 3.1.7 on 2021-05-13 16:47

from django.db import migrations
import mhoapp.theme.blocks.Separator
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_auto_20210513_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpage',
            name='left_content',
            field=wagtail.core.fields.StreamField([('Separator', mhoapp.theme.blocks.Separator()), ('headingH1', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock())])), ('headingH2', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock())])), ('paragraph', wagtail.core.blocks.StructBlock([('text_size', wagtail.core.blocks.ChoiceBlock(choices=[('small', 'Small'), ('normal', 'Normal')], icon='title')), ('paragraph', wagtail.core.blocks.RichTextBlock())])), ('quote', wagtail.core.blocks.BlockQuoteBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock())], default=''),
        ),
    ]
