# Generated by Django 3.1.7 on 2021-02-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20210226_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeCategory',
        ),
    ]
