# Generated by Django 3.1.7 on 2021-05-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsvg', '0002_svg_edit_code'),
        ('partners', '0007_delete_typecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnertypepage',
            name='intro',
        ),
        migrations.AddField(
            model_name='partnertypepage',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailsvg.svg'),
        ),
    ]
