# Generated by Django 3.1.7 on 2021-05-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20210506_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnertypepage',
            old_name='logo',
            new_name='icon',
        ),
    ]
