# Generated by Django 3.1.7 on 2021-05-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_auto_20210506_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerpage',
            name='name',
        ),
    ]
