# Generated by Django 3.1.7 on 2021-09-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0020_auto_20210918_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcepage',
            old_name='headingColLeft',
            new_name='leftColumn',
        ),
        migrations.RenameField(
            model_name='resourcepage',
            old_name='headingColRight',
            new_name='rightColumn',
        ),
    ]
