# Generated by Django 3.1.7 on 2021-09-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0023_auto_20210918_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcepage',
            old_name='left_column',
            new_name='left_column_content',
        ),
        migrations.RenameField(
            model_name='resourcepage',
            old_name='right_column',
            new_name='right_column_content',
        ),
    ]
